// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpacexWatchApp.Data;

#nullable disable

namespace SpacexWatchApp.Migrations
{
    [DbContext(typeof(LaunchesContext))]
    [Migration("20240724224610_InitalCreate")]
    partial class InitalCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SpacexWatchApp.Models.SavedLaunches", b =>
                {
                    b.Property<int>("FlightNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Upcoming")
                        .HasColumnType("bit");

                    b.HasKey("FlightNumber");

                    b.ToTable("SavedLaunches");
                });
#pragma warning restore 612, 618
        }
    }
}
